'\" t
.\"     Title: ostree remote
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/17/2017
.\"    Manual: ostree remote
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE REMOTE" "1" "" "OSTree" "ostree remote"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-remote \- Control remote repository configuration
.SH "SYNOPSIS"
.HP \w'\fBostree\ remote\ add\fR\ 'u
\fBostree remote add\fR [OPTIONS...] {NAME} {URL} [BRANCH...]
.HP \w'\fBostree\ remote\ delete\fR\ 'u
\fBostree remote delete\fR {NAME}
.HP \w'\fBostree\ remote\ show\-url\fR\ 'u
\fBostree remote show\-url\fR {NAME}
.HP \w'\fBostree\ remote\ list\fR\ 'u
\fBostree remote list\fR [OPTIONS...] {NAME}
.HP \w'\fBostree\ remote\ gpg\-import\fR\ 'u
\fBostree remote gpg\-import\fR [OPTIONS...] {NAME} [KEY\-ID...]
.HP \w'\fBostree\ remote\ refs\fR\ 'u
\fBostree remote refs\fR {NAME}
.HP \w'\fBostree\ remote\ summary\fR\ 'u
\fBostree remote summary\fR [OPTIONS...] {NAME}
.HP \w'\fBostree\ remote\ add\-cookie\fR\ 'u
\fBostree remote add\-cookie\fR {NAME} {DOMAIN} {PATH} {COOKIE_NAME} {VALUE}
.HP \w'\fBostree\ remote\ delete\-cookie\fR\ 'u
\fBostree remote delete\-cookie\fR {NAME} {DOMAIN} {PATH} {COOKIE_NAME} {VALUE}
.HP \w'\fBostree\ remote\ list\-cookies\fR\ 'u
\fBostree remote list\-cookies\fR {NAME}
.SH "DESCRIPTION"
.PP
Changes remote repository configurations\&. The NAME refers to the name of the remote\&.
.PP
The
\fBgpg\-import\fR
subcommand can associate GPG keys to a specific remote repository for use when pulling signed commits from that repository (if GPG verification is enabled)\&.
.PP
The GPG keys to import may be in binary OpenPGP format or ASCII armored\&. The optional
[KEY\-ID]
list can restrict which keys are imported from a keyring file or input stream\&. All keys are imported if this list is omitted\&. If neither
\fB\-\-keyring\fR
nor
\fB\-\-stdin\fR
options are given, then keys are imported from the user\*(Aqs personal GPG keyring\&.
.PP
The various cookie related command allow management of a remote specific cookie jar\&.
.SH "\*(AQADD\*(AQ OPTIONS"
.PP
\fB\-\-set\fR="KEY=VALUE"
.RS 4
Set config option KEY=VALUE for remote\&.
.RE
.PP
\fB\-\-no\-gpg\-verify\fR
.RS 4
Disable GPG verification\&.
.RE
.PP
\fB\-\-gpg\-import\fR=FILE
.RS 4
Import one or more GPG keys from a file\&.
.sp
Equivalent to
\fBostree remote gpg\-import \-\-keyring=FILE\fR\&.
.RE
.SH "\*(AQLIST\*(AQ OPTIONS"
.PP
\fB\-u, \-\-show\-urls\fR
.RS 4
Show remote URLs in list
.RE
.SH "\*(AQGPG\-IMPORT\*(AQ OPTIONS"
.PP
\fB\-k, \-\-keyring\fR=FILE
.RS 4
Import one or more keys from a file\&.
.sp
This option may be repeated to import from multiple files, but may not be used in combination with
\fB\-\-stdin\fR\&.
.RE
.PP
\fB\-\-stdin\fR
.RS 4
Import one or more keys from standard input\&.
.sp
This option may not be used in combination with
\fB\-\-keyring\fR\&.
.RE
.SH "\*(AQSUMMARY\*(AQ OPTIONS"
.PP
\fB\-\-raw\fR
.RS 4
Show raw variant data
.RE
.SH "EXAMPLE"
.PP
\fB$ ostree remote show\-url local\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        http://192\&.168\&.122\&.1/repo
.fi
.if n \{\
.RE
.\}
