'\" t
.\"     Title: ostree admin upgrade
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/19/2017
.\"    Manual: ostree admin upgrade
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE ADMIN UPGRADE" "1" "" "OSTree" "ostree admin upgrade"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-admin-upgrade \- Construct new tree from current origin and deploy it, if it changed
.SH "SYNOPSIS"
.HP \w'\fBostree\ admin\ upgrade\fR\ 'u
\fBostree admin upgrade\fR [OPTIONS...]
.SH "DESCRIPTION"
.PP
Downloads the latest version of the current ref from the build server and deploys it, if it changed\&. Reboot the machine for the changes to take effect\&. These phases can be split via
\fB\-\-pull\-only\fR
and
\fB\-\-deploy\-only\fR\&.
.SH "OPTIONS"
.PP
\fB\-\-os\fR="STATEROOT"
.RS 4
Use a different operating system root than the current one\&.
.RE
.PP
\fB\-\-pull\-only\fR
.RS 4
Only perform a pull into the repository; do not create a deployment\&. This option can hence safely be used in a background scheduled job with the assurance of not changing system state\&.
.RE
.PP
\fB\-\-deploy\-only\fR
.RS 4
Create a new deployment from the latest commit in the tracked origin refspec\&. This option is intended to be used by a scheduled system that detected changes via
\fB\-\-pull\-only\fR, and is ready to deploy them\&.
.RE
.PP
\fB\-\-reboot\fR,\fB\-r\fR
.RS 4
Reboot after a successful upgrade\&.
.RE
.PP
\fB\-\-allow\-downgrade\fR
.RS 4
Permit deployment of chronologically older trees\&.
.RE
.PP
\fB\-\-override\-commit\fR="CHECKSUM"
.RS 4
Deploy CHECKSUM instead of the latest tree\&.
.RE
.SH "EXAMPLE"
.PP
\fB$ ostree admin upgrade\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        No update available\&.
.fi
.if n \{\
.RE
.\}
