'\" t
.\"     Title: ostree admin init-fs
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 11/23/2016
.\"    Manual: ostree admin init-fs
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE ADMIN INIT\-F" "1" "" "OSTree" "ostree admin init-fs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-admin-init-fs \- Initialize a new root filesystem
.SH "SYNOPSIS"
.HP \w'\fBostree\ admin\ init\-fs\fR\ 'u
\fBostree admin init\-fs\fR [OPTIONS...] {PATH}
.SH "DESCRIPTION"
.PP
Initialize an empty physical root filesystem in the designated PATH, with normal toplevels and correct permissions for each directory\&. Primarily useful for operating system installers\&.
.SH "EXAMPLE"
.PP
\fB$ mkdir /example\fR
.PP
\fB$ ostree admin init\-fs /example\fR
.PP
\fB$ ls /example \fR
.PP
\fIboot\fR\ \&\ \&
\fIdev\fR\ \&\ \&
\fIhome\fR\ \&\ \&
\fIostree\fR\ \&\ \&
\fIproc\fR\ \&\ \&
\fIroot\fR\ \&\ \&
\fIrun\fR\ \&\ \&
\fIsys\fR\ \&\ \&
\fItmp\fR
