'\" t
.\"     Title: ostree admin config-diff
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 01/19/2017
.\"    Manual: ostree admin config-diff
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE ADMIN CONFIG\" "1" "" "OSTree" "ostree admin config-diff"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-admin-config-diff \- Diff current /etc configuration versus default
.SH "SYNOPSIS"
.HP \w'\fBostree\ admin\ config\-diff\fR\ 'u
\fBostree admin config\-diff\fR [OPTIONS...]
.SH "DESCRIPTION"
.PP
Prints the differences between the current /etc directory and the default configuration in /usr/etc\&. Newly added files (present in /etc but not in /usr/etc) will be prefixed with \*(AqA\*(Aq\&. Modified files will be prefixed with \*(AqM\*(Aq, and deleted files with \*(AqD\*(Aq\&.
.SH "OPTIONS"
.PP
\fB\-\-os\fR="OSNAME"
.RS 4
Use a different operating system root than the current one\&.
.RE
.SH "EXAMPLE"
.PP
\fB$ ostree admin config\-diff\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        M   shadow
        A   example\&.txt
	
.fi
.if n \{\
.RE
.\}
