'\" t
.\"     Title: ostree admin undeploy
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/12/2016
.\"    Manual: ostree admin undeploy
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE ADMIN UNDEPLO" "1" "" "OSTree" "ostree admin undeploy"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-admin-undeploy \- Delete deployment at a given index
.SH "SYNOPSIS"
.HP \w'\fBostree\ admin\ undeploy\fR\ 'u
\fBostree admin undeploy\fR {INDEX}
.SH "DESCRIPTION"
.PP
Deletes the deployment at INDEX\&. INDEX must be in range and not reference the currently booted deployment\&.
.SH "EXAMPLE"
.PP
\fB$ ostree admin status\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        * gnome\-ostree 67e382b11d213a402a5313e61cbc69dfd5ab93cb07\&.0
            origin refspec: gnome\-ostree/buildmaster/x86_64\-runtime
          gnome\-ostree ce19c41036cc45e49b0cecf6b157523c2105c4de1c\&.0
            origin refspec: gnome\-ostree/buildmaster/x86_64\-runtime
.fi
.if n \{\
.RE
.\}
.PP
\fB$ ostree admin undeploy 1\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        Transaction complete; bootconfig swap: no deployment count change: \-1)
        Freed objects: 326\&.5 kB
        Deleted deployment ce19c41036cc45e49b0cecf6b157523c2105c4de1c\&.0
.fi
.if n \{\
.RE
.\}
.PP
\fB$ ostree admin status\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        * gnome\-ostree 67e382b11d213a402a5313e61cbc69dfd5ab93cb07\&.0
            origin refspec: gnome\-ostree/buildmaster/x86_64\-runtime
.fi
.if n \{\
.RE
.\}
