'\" t
.\"     Title: ostree refs
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 11/03/2016
.\"    Manual: ostree refs
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE REFS" "1" "" "OSTree" "ostree refs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-refs \- List refs
.SH "SYNOPSIS"
.HP \w'\fBostree\ refs\fR\ 'u
\fBostree refs\fR [OPTIONS...] [PREFIX]
.SH "DESCRIPTION"
.PP
Lists all refs available on the host\&. If specified, PREFIX assigns the refspec prefix; default prefix is null, which lists all refs\&.
.SH "OPTIONS"
.PP
\fB\-\-list\fR
.RS 4
For historical reasons,
refs
without this option will strip the specified prefix from the output\&. Normally, one wants to see the full ref, so providing this option ensures the refs are printed in full, rather than truncated\&.
.RE
.PP
\fB\-\-delete\fR
.RS 4
Delete refs which match PREFIX, rather than listing them\&. If you are trying to reclaim space, you will then need to
\fBostree prune\fR
or
\fBostree admin cleanup\fR\&.
.RE
.SH "EXAMPLE"
.PP
\fB$ ostree refs\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        my\-branch
        gnome\-ostree/buildmaster/x86_64\-runtime
.fi
.if n \{\
.RE
.\}
