'\" t
.\"     Title: ostree diff
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/17/2017
.\"    Manual: ostree diff
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE DIFF" "1" "" "OSTree" "ostree diff"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-diff \- Compare a directory against a revision
.SH "SYNOPSIS"
.HP \w'\fBostree\ diff\fR\ 'u
\fBostree diff\fR [OPTIONS...] {REV} {TARGETDIR}
.SH "DESCRIPTION"
.PP
Compare directory TARGETDIR against revision REV\&. Shows files and directories modified, added, and deleted\&. If there is a file in TARGETDIR not in REV, it will show with an "A" for "added"\&. If a file in REV is not in TARGETDIR, it shows "D" for "deleted"\&. "M" for "modified" will also show\&.
.SH "OPTIONS"
.PP
\fB\-\-stats\fR
.RS 4
Print various statistics\&.
.RE
.PP
\fB\-\-fs\-diff\fR
.RS 4
Print filesystem diff\&.
.RE
.PP
\fB\-\-owner\-uid\fR
.RS 4
Use file ownership user id for local files\&.
.RE
.PP
\fB\-\-owner\-gid\fR
.RS 4
Use file ownership group id for local files\&.
.RE
.SH "EXAMPLE"
.PP
\fB$ ostree diff my\-branch^ my\-branch\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        A   /testdirectory
        M   /helloworld\&.txt
.fi
.if n \{\
.RE
.\}
.PP
\fB$ ostree diff my\-branch my\-branch^\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        D   /testdirectory
        M   /helloworld\&.txt
.fi
.if n \{\
.RE
.\}
