'\" t
.\"     Title: ostree ls
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/12/2016
.\"    Manual: ostree ls
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE LS" "1" "" "OSTree" "ostree ls"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-ls \- List file paths
.SH "SYNOPSIS"
.HP \w'\fBostree\ ls\fR\ 'u
\fBostree ls\fR [OPTIONS...] {COMMIT} [PATHS...]
.SH "DESCRIPTION"
.PP
Prints a list of file paths within the given commit, and within the given path(s) if specified\&. The first letter of the file line output specifies the type: "\-" for regular file, "d" for directory, "l" for symbolic link\&. See EXAMPLE section for more detail on the specific output\&.
.SH "OPTIONS"
.PP
\fB\-\-dironly\fR,\fB\-d\fR
.RS 4
Do not recurse into directory arguments\&.
.RE
.PP
\fB\-\-recursive\fR,\fB\-R\fR
.RS 4
Print directories recursively\&.
.RE
.PP
\fB\-\-checksum\fR,\fB\-C\fR
.RS 4
Print checksum\&.
.RE
.PP
\fB\-\-xattrs\fR,\fB\-X\fR
.RS 4
Print extended attributes\&.
.RE
.PP
\fB\-\-nul\-filenames\-only\fR
.RS 4
Print only filenames, NUL separated\&.
.RE
.SH "EXAMPLE"
.PP
\fB$ ostree ls my\-branch\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        d00644 0 0    0 /
        \-00644 0 0    2 /helloworld\&.txt
        d00755 0 0    0 /testdirectory
.fi
.if n \{\
.RE
.\}
.PP
Here, the first column is the file\-type symbol (as explained in the DESCRIPTION section) followed by the S_IFMT file type\&. The next two columns (here: 0 0) are respectively the user ID and group ID for the file\&. After the break, the next number represents that file\*(Aqs standard size\&. The final column is the file path\&.
