'\" t
.\"     Title: ostree gpg-sign
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 04/05/2017
.\"    Manual: ostree gpg-sign
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE GPG\-SIGN" "1" "" "OSTree" "ostree gpg-sign"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-gpg-sign \- Sign a commit
.SH "SYNOPSIS"
.HP \w'\fBostree\ gpg\-sign\fR\ 'u
\fBostree gpg\-sign\fR [OPTIONS...] {COMMIT} {KEY\-ID...}
.SH "DESCRIPTION"
.PP
Add a new signature to a commit for each specified GPG key\&. Note that currently, this will append a new signature even if the commit is already signed with a given key\&.
.SH "OPTIONS"
.PP
\fB\-\-delete\fR
.RS 4
Delete signatures having any of the GPG KEY\-IDs\&.
.RE
.PP
\fB\-\-gpg\-homedir\fR="HOMEDIR"
.RS 4
GPG Homedir to use when looking for keyrings\&.
.RE
