'\" t
.\"     Title: ostree checksum
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/05/2016
.\"    Manual: ostree checksum
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE CHECKSUM" "1" "" "OSTree" "ostree checksum"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-checksum \- Checksum a file or directory
.SH "SYNOPSIS"
.HP \w'\fBostree\ checksum\fR\ 'u
\fBostree checksum\fR {PATH}
.SH "DESCRIPTION"
.PP
Generates a checksum for a given file or directory\&.
.SH "EXAMPLE"
.PP
\fB$ ostree checksum file1\fR
.sp
.if n \{\
.RS 4
.\}
.nf
        67e382b11d213a402a5313e61cbc69dfd5ab93cb07fbb8b71c2e84f79fa5d7dc
.fi
.if n \{\
.RE
.\}
