'\" t
.\"     Title: ostree.repo-config
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/05/2016
.\"    Manual: ostree.repo-config
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE\&.REPO\-CONFI" "5" "" "OSTree" "ostree.repo-config"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree.repo-config \- OSTree repository configuration
.SH "DESCRIPTION"
.PP
The
config
file in an OSTree repository is a "keyfile" in the
\m[blue]\fBXDG Desktop Entry Specification\fR\m[]\&\s-2\u[1]\d\s+2
format\&. It has several global flags, as well as zero or more remote entries which describe how to access remote repositories\&.
.PP
See
\fBostree.repo\fR(5)
for more information about OSTree repositories\&.
.SH "[CORE] SECTION OPTIONS"
.PP
Repository\-global options\&. The following entries are defined:
.PP
\fImode\fR
.RS 4
One of
bare
or
archive\-z2\&.
.RE
.PP
\fIrepo_version\fR
.RS 4
Currently, this must be set to
1\&.
.RE
.PP
\fIcommit\-update\-summary\fR
.RS 4
Boolean value controlling whether or not to automatically update the summary file after a commit\&. Defaults to
false\&.
.RE
.PP
\fIfsync\fR
.RS 4
Boolean value controlling whether or not to ensure files are on stable storage when performing operations such as commits, pulls, and checkouts\&. Defaults to
true\&.
.sp
If you disable fsync, OSTree will no longer be robust against kernel crashes or power loss\&.
.sp
You might choose to disable this for local development repositories, under the assumption they can be recreated from source\&. Similarly, you could disable for a mirror where you could re\-pull\&.
.sp
For the system repository, you might choose to disable fsync if you have uninterruptable power supplies and a well tested kernel\&.
.RE
.SH "[REMOTE "NAME"] SECTION OPTIONS"
.PP
Describes a remote repository location\&.
.PP
\fIurl\fR
.RS 4
Must be present; declares URL for accessing this remote\&. The only supported schemes are the moment are
file,
http, and
https\&.
.RE
.PP
\fIproxy\fR
.RS 4
A string value, if given should be a URL for a HTTP proxy to use for access to this repository\&.
.RE
.PP
\fIgpg\-verify\fR
.RS 4
A boolean value, defaults to true\&. Controls whether or not OSTree will require commits to be signed by a known GPG key\&. For more information, see the
\fBostree\fR(1)
manual under GPG\&.
.RE
.PP
\fIgpg\-verify\-summary\fR
.RS 4
A boolean value, defaults to false\&. Controls whether or not OSTree will check if the summary is signed by a known GPG key\&. For more information, see the
\fBostree\fR(1)
manual under GPG\&.
.RE
.PP
\fItls\-permissive\fR
.RS 4
A boolean value, defaults to false\&. By default, server TLS certificates will be checked against the system certificate store\&. If this variable is set, any certificate will be accepted\&.
.RE
.PP
\fItls\-client\-cert\-path\fR
.RS 4
Path to file for client\-side certificate, to present when making requests to this repository\&.
.RE
.PP
\fItls\-client\-key\-path\fR
.RS 4
Path to file containing client\-side certificate key, to present when making requests to this repository\&.
.RE
.PP
\fItls\-ca\-path\fR
.RS 4
Path to file containing trusted anchors instead of the system CA database\&.
.RE
.SH "/ETC/OSTREE/REMOTES.D"
.PP
In addition to the
/ostree/repo/config
file, remotes may also be specified in
/etc/ostree/remotes\&.d\&. The remote configuration file must end in
\&.conf; files whose name does not end in
\&.conf
will be ignored\&.
.SH "PER-REMOTE GPG KEYRINGS AND VERIFICATION"
.PP
OSTree supports a per\-remote GPG keyring\&. For more information see
\fBostree\fR(1)\&. in the section
GPG verification\&.
.SH "SEE ALSO"
.PP
\fBostree\fR(1),
\fBostree.repo\fR(5)
.SH "NOTES"
.IP " 1." 4
XDG Desktop Entry Specification
.RS 4
\%http://standards.freedesktop.org/desktop-entry-spec/latest/
.RE
