'\" t
.\"     Title: ostree admin set-origin
.\"    Author: Colin Walters <walters@verbum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 11/03/2016
.\"    Manual: ostree admin set-origin
.\"    Source: OSTree
.\"  Language: English
.\"
.TH "OSTREE ADMIN SET\-OR" "1" "" "OSTree" "ostree admin set-origin"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ostree-admin-set-origin \- Change the "origin" (location for upgrades)
.SH "SYNOPSIS"
.HP \w'\fBostree\ admin\ set\-origin\ \fR\ 'u
\fBostree admin set\-origin \fR {REMOTENAME} {URL} [BRANCH]
.SH "DESCRIPTION"
.PP
Add a new remote named
\fIREMOTENAME\fR
(if it does not already exist)\&. Then change the origin file for the current deployment\&. This is the ref that will be "tracked" and upgraded with
\fBostree admin upgrade\fR\&.
.SH "OPTIONS"
.PP
\fB\-\-set\fR=KEY=VALUE
.RS 4
Set an option for the remote\&.
.RE
.PP
\fB\-\-index\fR=INDEX
.RS 4
Change the origin of the deployment numbered
\fIINDEX\fR
(starting from 0)\&.
.RE
.SH "EXAMPLE"
.PP
\fB$ ostree admin set\-origin exampleos http://os\&.example\&.com/repo exampleos/10\&.0/master/router\fR
