#!/bin/sh

set -e
exec 2>&1
set -x

cd "$AUTOPKGTEST_TMP"

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

cat > trivial.c <<EOF
#include <ostree.h>

int main (void)
{
    g_object_unref (ostree_repo_new_default ());
    return 0;
}
EOF

# Deliberately word-splitting, that's how pkg-config works:
# shellcheck disable=SC2046
"${CROSS_COMPILE}gcc" -o trivial trivial.c $("${CROSS_COMPILE}pkg-config" --cflags --libs ostree-1 gobject-2.0)
test -x trivial
./trivial
echo "OK"
