#!/bin/sh

set -e
exec 2>&1

N=3
passed=0

for i in `seq 1 $N`; do
	if gnome-desktop-testing-runner ostree/test-local-pull.sh.test; then
		passed=$(( $passed + 1))
	fi
done

echo "test-local-pull: passed $passed/$N attempts"

if [ "$passed" -ne "$N" ]; then
	exit 1
fi
